# Generated by Django 5.2b1 on 2025-03-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainers_Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=30)),
                ('trainer_image', models.ImageField(upload_to='images/')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('facebook_img', models.ImageField(blank=True, upload_to='images/')),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('twitter_img', models.ImageField(blank=True, upload_to='images/')),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('instagram_img', models.ImageField(blank=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
