# Generated by Django 5.2b1 on 2025-03-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_info_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_section',
            name='item_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
