# Generated by Django 5.2b1 on 2025-03-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_section',
            name='item_name',
            field=models.CharField(max_length=50),
        ),
    ]
