# Generated by Django 5.2b1 on 2025-03-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_info_section_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_section',
            name='copy_info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
